## 异常的抛与接

### 再说异常

Error通常是很难发现的，出现后也很难处理：

```java
public class ErrorDemo {

	public static void fun(int a) {
		System.out.println("fun(" + a + ")");
		if ( a == 0)
			return;
		else
			fun(a-1);
	}
	
	public static void main(String[] args) {
		//java.lang.StackOverflowError
		fun(500000);
	}
}
```

相比之下，异常是应该应对的错误

* 异常是可以发现的
* 异常是可以有多种处理方式的

### 一个异常的故事

举个例子，放假了，想出去玩，出去玩就要开车，结果发现车子没油，结果只能家里蹲。

能汇报没有油的车：

```java
public class Car {
	
	double gas = 10;
	
	public Car(double gas) {
		this.gas = gas;
	}
	
	public void startEngine() throws Exception {
		if (gas < 1)
			throw new Exception("车子没油了！");
	}

}
```

能知道车子没油的人：

```java
public class Driver {
	
	public void drive(Car car) throws Exception {
		car.startEngine(); //点火
		//然后才能开车
	}

}
```

如果没油了，可以去加油的车子主人：

```java
public class Owner {
	
	Car car = null;
	double money = 100;
	
	public Owner(Car car) {
		this.car = car;
	}
	
	public void addGas(int liter) throws NoMoneyException {
		if (money > liter * 5.5) {
			car.fillOil(liter);
			money = money - liter*5.5;
		} else
			throw new NoMoneyException("钱不够啊～～～～");
	}

	public Car getCar() {
		return car;
	}

	public double getMoney() {
		return money;
	}

	public void setMoney(double money) {
		this.money = money;
	}
} 
```

### throw、try、catch和finally的规则

（1）异常的抛出(throw)：throw 异常对象

（2）异常的抛出(throw)：执行了可能抛出异常的方法

（3）异常的抛出(throw)：执行了一段可能抛出异常的代码

（4）异常的处理：抛给调用该方法的方法

（5）异常的处理：放在try里执行，通过catch捕获

（6）异常的处理：不处理……极不推荐这么做

（7）catch的依次捕获

（8）finally的代码：如果写了finally的代码段，必定会被执行

```java
public class Main {

	public static void main(String[] args) {
		
		Car car = new Car(0.5); //很少油
		Owner owner = new Owner(car);		
		Driver driver = new Driver();
		
		try {
			driver.drive(owner.getCar());
		} catch (NoOilException e) {
			//（5）异常的处理：放在try里执行，通过catch捕获
			System.out.println(e.getMessage());
			try {
				int amount = 10;
				owner.addGas(amount);
				System.out.println("加了"+amount+"升油，可以开车了");
			} catch (NoMoneyException e1) {
				System.out.println(e1.getMessage());
				System.out.println("家里墩～");
			} catch (TooMuchOilException e1) {
				System.out.println(e1.getMessage());
				System.out.println("家里墩～");
			}  finally {
				System.out.println("加油结束！");
			}			
		} finally {
			System.out.println("故事结束！");
		}

	}

}
```

